[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "php -S 0.0.0.0:$PORT"
  healthcheckPath = "/"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[variables]
  PHP_VERSION = "8.1"
  NIXPACKS_PHP_ROOT_DIR = "."