services:
  - type: web
    name: donation-platform
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: PHP_VERSION
        value: "8.1"
      - key: DB_HOST
        fromDatabase:
          name: donation-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: donation-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: donation-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: donation-db
          property: password

databases:
  - name: donation-db
    plan: free
    databaseName: donation_platform